name: Sidemenu app pipeline

on: 
  push:
    branches: 
      - main
    paths:
      - 'apps/Sidemenu/**'
      - 'libs/**'
      
jobs:
  web-deploy:

    name: Deploy Sidemenu app
    runs-on: ubuntu-latest
    # Start stage


    # Use template with parameters
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2


    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    # - name: cd app && ls && pwd
    #   run: ls && cd app && ls && pwd

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build-list